### ISSUE TITLE
Core dump when sending a file to the master (instead of the storage)

### ISSUE THREAD

**Issue by Dubrzr** [Dubrzr/MP2P#2]
To reproduce:
Launch the master, then send a file with the client.

**Comment by thegameg** [comment]
The problem came from a `delete` on an object that was allocated on the stack. It's probably part of the pseudo-code from the callbacks.

**Comment by RustyCrowbar** [comment]
"It's probably part of the pseudo-code from the callbacks." Sorry. :p
